Repository ViktorHrimli/Actum, pull requests merged in 2023-12, with the labels that each got.

#308 New sitemap
  package-lock.json
  package.json
  src/assets/json/reviews.json
  src/libs/modal/formComponent/FormComponent.jsx
  src/libs/modal/modalThanks/modalThanks.jsx
  src/shared/components/about/About.module.scss
  src/shared/components/siteMap/siteMap.jsx
  src/shared/components/siteMap/siteMap.module.scss
  src/shared/components/stepLawyers/StepsLawyers.module.scss
Labels: bug, duplicate

#311 fix bag
  src/app/paid-priority-army/[name]/page.jsx
  src/assets/json/reviews.json
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
Labels: bug, duplicate

#312 Admin panel
  .env
  src/app/paid-blitz-consultation/[name]/page.jsx
  src/app/paid-blitz-consultation/page.jsx
  src/app/paid-priority-army-kiev/[name]/page.jsx
  src/app/paid-priority-army-kiev/page.jsx
  src/app/paid-priority-army-mob/[name]/page.jsx
  src/app/paid-priority-army-mob/page.jsx
  src/app/paid-priority-army-ur/[name]/page.jsx
  src/app/paid-priority-army-ur/page.jsx
  src/app/paid-priority-army/[name]/page.jsx
  src/app/paid-priority-consultation/[name]/page.jsx
  src/app/paid-priority-consultation/page.jsx
  src/assets/json/reviews.json
  src/libs/components/card/Card.jsx
  src/libs/components/response/Response.jsx
  src/libs/components/response/Response.module.scss
  src/libs/pages/components/QuestionList/Accordion.jsx
  src/libs/pages/components/priceCards/items/Items.jsx
  src/libs/pages/components/successfulBusiness/SuccessfulBusiness.jsx
  src/libs/pages/components/successfulBusiness/SuccessfulBusiness.module.scss
  src/shared/components/path/Path.jsx
  src/shared/helpers/queryBuilder.js
Labels: bug, duplicate, enhancement

#313 fix bagl
  .env
  i18n-config.js
  next.config.js
  src/app/layout.jsx
  src/assets/json/reviews.json
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/components/contactPanel/libs/enums.js
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/NavSelectItem/NavSelectItem.module.scss
  src/libs/components/response/Response.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/libs/modal/formComponent/enumsForm/enumsForm.js
  src/libs/modal/modalForm/enumsForm/enumsForm.js
Labels: bug, duplicate, enhancement

#316 fix bag and make localization
  src/app/html-sitemap/page.jsx
  src/app/ru/html-sitemap/page.jsx
  src/assets/json/reviews.json
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/pages/contacts/contacts/Contacts.jsx
  src/libs/pages/contacts/contacts/Contacts.module.scss
  src/libs/pages/publics/currentPublication/CurrentPublication.jsx
  src/shared/components/nestedPageHero/NestedHero.jsx
  src/shared/components/siteMap/siteMap.jsx
Labels: bug, duplicate

#319 Loacale
  next.config.js
  src/app/layout.jsx
  src/app/paid-priority-army-kiev/page.jsx
  src/app/ru/paid-priority-consultation/page.jsx
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/components/footer/Footer.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/components/ourDirections/criminalMatters/CriminalMattrs.jsx
  src/libs/components/ourDirections/familyMatters/FamilyMattrs.jsx
  src/libs/components/ourDirections/militaryMatters/MilitaryMattrs.jsx
Labels: duplicate, enhancement, good first issue

#324 Loacale
  public/robots.txt
  src/app/ru/paid-priority-army-kiev/[name]/page.jsx
  src/app/ru/paid-priority-army-mob/[name]/page.jsx
  src/app/ru/paid-priority-army-ur/[name]/page.jsx
  src/app/ru/paid-priority-army/[name]/page.jsx
  src/app/ru/services/[name]/[...slug]/page.jsx
  src/app/ru/services/[name]/page.jsx
  src/assets/json/reviews.json
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/components/nav/SelectNav/Select.jsx
  src/shared/helpers/queryBuilder.js
  src/shared/helpers/seoBuilder.js
  src/shared/services/api/getLawyerDynamicPage.js
  src/shared/services/api/getSeoDynamicPage.js
Labels: bug, duplicate, enhancement

#325 fix bag
  src/app/paid-priority-army-kiev/[name]/page.jsx
  src/app/paid-priority-army-mob/[name]/page.jsx
  src/app/paid-priority-army-ur/[name]/page.jsx
  src/assets/json/reviews.json
  src/libs/components/response/Response.module.scss
  src/libs/pages/components/priceCards/items/Items.jsx
  src/libs/pages/components/priceCards/items/Items.module.scss
  src/libs/pages/components/priceCards/items/cards/cardB/CardB.module.scss
Labels: bug, duplicate, enhancement

#327 Fix bag
  .env
  package-lock.json
  package.json
  public/robots.txt
  src/app/api/send/route.js
  src/app/ru/services/[name]/[...slug]/page.jsx
  src/app/services/[name]/[...slug]/page.jsx
  src/app/sitemap.js
  src/assets/json/reviews.json
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/pages/components/QuestionList/Accordion.jsx
  src/shared/components/click/Click.jsx
  src/shared/components/email-template/email-template.jsx
  src/shared/components/siteMap/siteMap.jsx
  src/shared/enums/app/app.js
  src/shared/enums/app/slugObj.js
  src/shared/enums/enum.js
  src/shared/helpers/helpers.js
  src/shared/helpers/parseQueryNestedPage.js
Labels: bug, duplicate, enhancement

#328 fix bag
  src/app/globals.scss
  src/assets/json/reviews.json
  src/libs/components/header/Header.jsx
Labels: bug, duplicate, enhancement

#332 fix bag
  .env
  src/app/api/send/route.js
  src/app/layout.jsx
  src/app/robots.js
  src/app/sitemap.js
  src/libs/components/card/Card.jsx
  src/libs/components/footer/Footer.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/components/side_bar/SideBar.jsx
  src/libs/pages/components/QuestionList/Accordion.jsx
  src/libs/pages/publics/Item/Item.jsx
  src/shared/components/click/Click.jsx
  src/shared/components/click/Click.module.scss
  src/shared/components/formSection/FormSection.jsx
Labels: bug, duplicate, enhancement

#333 fix bag
  src/app/globals.scss
Labels: bug, duplicate

#334 fix bag
  src/app/globals.scss
Labels: bug, duplicate

#337 Loacale
  .env
  next.config.js
  src/app/api/send/route.js
  src/app/layout.jsx
  src/app/services/[name]/[...slug]/page.jsx
  src/libs/pages/contacts/contacts/Contacts.jsx
  src/shared/components/form/Form.jsx
  src/shared/enums/app/slugObj.js
  src/shared/helpers/seoBuilder.js
Labels: bug, duplicate, enhancement, good first issue

#339 Loacale
  src/app/html-sitemap/page.jsx
  src/app/layout.jsx
  src/assets/json/reviews.json
  src/libs/pages/components/successfulBusiness/SuccessfulBusiness.jsx
  src/libs/pages/publics/Publics.jsx
  src/libs/pages/publics/Publics.module.scss
  src/libs/pages/publics/pagination/Pagination.jsx
  src/libs/pages/publics/pagination/Pagination.module.scss
  src/libs/pages/publics/publics_list/PublicList.jsx
  src/shared/components/search/Search.jsx
  src/shared/helpers/seoBuilder.js
Labels: bug, duplicate, enhancement

#341 Loacale
  .env
  src/app/paid-priority-army-dnipro/page.jsx
  src/app/ru/paid-priority-army-dnipro/page.jsx
Labels: bug, duplicate, enhancement

#342 make lawyers static page
  src/app/api/rewiews/route.js
  src/app/paid-priority-army-kryvyi-rih/page.jsx
  src/app/paid-priority-army-lviv/page.jsx
  src/app/paid-priority-army-mykolaiv/page.jsx
  src/app/ru/paid-priority-army-kryvyi-rih/page.jsx
  src/app/ru/paid-priority-army-lviv/page.jsx
  src/app/ru/paid-priority-army-mykolaiv/page.jsx
  src/assets/svg/skeleton.jpg
  src/libs/components/card/Card.jsx
  src/shared/enums/app/slugObj.js
Labels: duplicate, enhancement

#344 fix bag
  src/app/500.jsx
  src/app/not-found.jsx
Labels: bug

#347 fix bag
  src/app/api/send/route.js
  src/libs/components/hero/Animations.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/shared/components/form/Form.jsx
  src/shared/helpers/seoBuilder.js
Labels: bug, duplicate

#349 Item prop
  .env
  src/app/blog-3-1/[name]/page.jsx
  src/app/layout.jsx
  src/app/ru/contacts/page.jsx
  src/libs/components/about_company/AboutCompany.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/libs/pages/components/QuestionList/QuestionsList.jsx
  src/shared/components/about/About.jsx
  src/shared/components/form/Form.jsx
Labels: bug, duplicate

#352 Item prop
  src/app/layout.jsx
  src/app/sitemap.js
  src/libs/components/btn_side_bar/BtnSideBar.jsx
  src/libs/components/card/Card.jsx
  src/libs/components/footer/Footer.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/pages/components/QuestionList/QuestionsList.jsx
  src/shared/components/scripts/Scripts.jsx
Labels: bug, duplicate

#359 fix bag
  src/app/api/rewiews/route.js
  src/app/api/send/route.js
  src/app/not-found.jsx
  src/libs/components/card/Card.jsx
  src/libs/components/hero/Animations.jsx
  src/libs/components/hero/Gradients.jsx
  src/libs/components/hero/Hero.jsx
  src/libs/components/hero/Hero.module.scss
  src/shared/components/nestedPageHero/NestedHero.jsx
  src/shared/components/nestedPageHero/NestedHero.module.scss
  src/shared/components/scripts/Scripts.jsx
Labels: duplicate, good first issue

#360 fix bag
  src/assets/json/reviews.json
  src/libs/pages/contacts/contacts/Contacts.jsx
  src/shared/components/scripts/Scripts.jsx
Labels: bug, duplicate

#361 fix bag
  src/shared/components/scripts/Scripts.jsx
Labels: bug, duplicate

#362 fix bag
  src/shared/components/scripts/Scripts.jsx
Labels: bug, duplicate

#363 fix bag
  src/app/services/[name]/page.jsx
  src/app/services/page.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/components/side_bar/SideBar.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/shared/components/form/Form.jsx
  src/shared/components/nestedPageHero/NestedHero.jsx
  src/shared/components/path/Path.jsx
  src/shared/helpers/sessionStorageManager.js
Labels: bug, duplicate

#377 fix bag
  src/app/api/rewiews/route.js
Labels: bug, duplicate

#378 Item prop
  src/libs/components/about_company/AboutCompany.jsx
  src/libs/components/card/Card.jsx
  src/libs/components/hero/Animations.jsx
  src/libs/components/hero/Gradients.jsx
  src/libs/components/nav/Navigation.jsx
  src/shared/components/about/About.jsx
  src/shared/components/scripts/Scripts.jsx
Labels: bug, duplicate

#400 Item prop
  src/app/not-found.jsx
  src/app/page.jsx
  src/app/ru/blog-3-1/[name]/page.jsx
  src/app/ru/blog-3-1/page.jsx
  src/app/ru/book/page.jsx
  src/app/ru/contacts/page.jsx
  src/app/ru/html-sitemap/[name]/page.jsx
  src/app/ru/html-sitemap/page.jsx
  src/app/ru/paid-blitz-consultation/page.jsx
  src/app/ru/paid-priority-army-dnipro/page.jsx
  src/app/ru/paid-priority-army-kiev/page.jsx
  src/app/ru/paid-priority-army-kryvyi-rih/page.jsx
  src/app/ru/paid-priority-army-lviv/page.jsx
  src/app/ru/paid-priority-army-mob/page.jsx
  src/app/ru/paid-priority-army-mykolaiv/page.jsx
  src/app/ru/paid-priority-army-ur/page.jsx
  src/app/ru/paid-priority-army/[name]/page.jsx
  src/app/ru/paid-priority-army/page.jsx
  src/app/ru/paid-priority-consultation/page.jsx
  src/app/ru/services/[name]/[...slug]/page.jsx
  src/app/ru/services/[name]/page.jsx
  src/app/ru/teamactum/page.jsx
  src/app/teamactum/page.jsx
  src/assets/svg/makoznak.png
  src/libs/components/header/Header.jsx
  src/libs/components/hero/Hero.jsx
  src/shared/components/scripts/Scripts.jsx
  src/shared/helpers/seoBuilder.js
Labels: bug, duplicate

#401 fix bag
  src/libs/components/header/Header.jsx
Labels: bug, duplicate

#408 Item prop
  src/app/not-found.jsx
  src/app/paid-blitz-consultation/page.jsx
  src/app/paid-priority-army-dnipro/page.jsx
  src/app/paid-priority-army-kiev/page.jsx
  src/app/paid-priority-army-kryvyi-rih/page.jsx
  src/app/paid-priority-army-lviv/page.jsx
  src/app/paid-priority-army-mob/page.jsx
  src/app/paid-priority-army-mykolaiv/page.jsx
  src/app/paid-priority-army-ur/page.jsx
  src/app/paid-priority-army/[name]/page.jsx
  src/app/paid-priority-army/page.jsx
  src/app/paid-priority-consultation/page.jsx
  src/libs/components/footer/Footer.jsx
  src/libs/components/header/Header.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/shared/helpers/sessionStorageManager.js
Labels: bug, duplicate

#413 fix bag
  src/shared/components/form/Form.jsx
  src/shared/helpers/sessionStorageManager.js
Labels: bug, duplicate

#414 fix bag
  src/app/ru/teamactum/page.jsx
Labels: bug, duplicate

#417 G
  src/libs/components/header/Header.jsx
  src/shared/components/form/Form.jsx
  src/shared/helpers/coockiesManager.js
  src/shared/helpers/helpers.js
  src/shared/helpers/sessionStorageManager.js
Labels: bug, duplicate, enhancement

#418 fix bag
  next.config.js
Labels: bug, duplicate

#419 fix bag
  next.config.js
  src/shared/helpers/coockiesManager.js
Labels: bug, duplicate

#420 fix bag
  package-lock.json
  package.json
  src/app/favicon.ico
  src/app/not-found.jsx
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/components/header/Header.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/shared/components/form/Form.jsx
  src/shared/helpers/coockiesManager.js
Labels: bug, duplicate

#421 fix bag
  src/libs/components/header/Header.jsx
Labels: bug

#422 fix bag
  src/shared/helpers/coockiesManager.js
Labels: bug, duplicate

#423 fix bag
  src/app/[...not-found]/page.js
  src/app/not-found.js
  src/libs/components/header/Header.jsx
Labels: bug, duplicate

#425 G
  src/app/blog-3-1/[name]/page.jsx
  src/app/html-sitemap/[name]/page.jsx
  src/app/paid-priority-army/[name]/page.jsx
  src/app/ru/html-sitemap/[name]/page.jsx
  src/app/ru/paid-priority-army/[name]/page.jsx
  src/app/ru/services/[name]/[...slug]/page.jsx
  src/app/ru/services/[name]/page.jsx
  src/app/services/[name]/[...slug]/page.jsx
  src/app/services/[name]/page.jsx
  src/libs/components/header/Header.jsx
  src/shared/helpers/coockiesManager.js
  src/shared/helpers/sessionStorageManager.js
Labels: bug, duplicate

#426 fix bag
  src/libs/components/header/Header.jsx
Labels: bug, duplicate

#428 fix bag
  src/app/ru/services/[name]/[slug]/page.jsx
  src/app/services/[name]/[slug]/page.jsx
Labels: bug, duplicate

#430 G
  package-lock.json
  package.json
  src/app/paid-priority-army/page.jsx
  src/libs/components/lazyLoadComponent/LazyLoad.jsx
Labels: bug, duplicate

#431 fix bag
  src/app/paid-priority-army/page.jsx
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/shared/components/form/Form.jsx
  src/shared/helpers/coockiesManager.js
Labels: bug, duplicate

#436 fix bag
  src/app/blog-3-1/[name]/page.jsx
  src/app/layout.jsx
  src/app/ru/blog-3-1/[name]/page.jsx
  src/app/ru/services/[name]/[...slug]/page.jsx
  src/app/services/[name]/[...slug]/page.jsx
  src/assets/json/reviews.json
  src/libs/components/header/Header.jsx
  src/shared/components/form/Form.jsx
  src/shared/helpers/coockiesManager.js
Labels: bug, duplicate

#440 G
  package-lock.json
  package.json
  src/app/layout.jsx
  src/libs/components/about_company/AboutCompany.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/hero/Animations.jsx
  src/libs/components/hero/Hero.jsx
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/components/nav/SelectNav/Select.jsx
  src/libs/pages/components/QuestionList/Accordion.jsx
  src/libs/pages/components/QuestionList/QuestionsList.jsx
  src/libs/pages/components/hero/HeroLawyers.jsx
  src/libs/pages/components/priceCards/items/Items.jsx
  src/libs/pages/components/priceCards/items/cards/cardB/CardB.jsx
  src/shared/components/nestedPageHero/NestedHero.jsx
  src/shared/components/path/Path.jsx
  src/shared/helpers/seoBuilder.js
  src/shared/services/api/getSeoDynamicPage.js
Labels: bug, duplicate, enhancement
