Repository ViktorHrimli/Actum, pull requests merged in 2023-11, with the labels that each got.

#272 add model lawyers pages;
  .env
  src/app/blog-3-1/[name]/page.jsx
  src/app/book/page.jsx
  src/app/paid-priority-army/[name]/page.jsx
  src/app/paid-priority-army/page.jsx
  src/app/paid-priority-crime/[name]/page.jsx
  src/app/paid-priority-crime/page.jsx
  src/app/paid-priority-family/[name]/page.jsx
  src/app/paid-priority-family/page.jsx
  src/app/ru/book/page.jsx
  src/app/ru/paid-priority-army/[name]/page.jsx
  src/app/ru/paid-priority-army/page.jsx
  src/app/ru/paid-priority-crime/[name]/page.jsx
  src/app/ru/paid-priority-crime/page.jsx
  src/app/ru/paid-priority-family/[name]/page.jsx
  src/app/ru/paid-priority-family/page.jsx
  src/libs/components/about/About.jsx
  src/libs/components/currentPublication/CurrentPublication.jsx
  src/libs/components/formSection/FormSection.jsx
  src/libs/pages/components/QuestionList/Accordion.jsx
  src/libs/pages/components/QuestionList/QuestionsList.jsx
  src/libs/pages/components/hero/HeroLawyers.jsx
  src/libs/pages/components/specialists/Specialists.jsx
  src/libs/pages/components/specialists/items/Items.jsx
  src/libs/pages/publics/Item/Item.jsx
  src/libs/pages/publics/libs/enums/enum.js
  src/libs/pages/publics/publics_list/PublicList.jsx
  src/libs/pages/services/components/description/Description.jsx
  src/shared/components/path/Path.jsx
  src/shared/helpers/queryBuilder.js
  src/shared/services/api/api.js
  src/shared/services/api/getArmyPage.js
  src/shared/services/api/getBlogPublication.js
  src/shared/services/api/getCrimePage.js
  src/shared/services/api/getFamilyPage.js
Labels: duplicate, enhancement, good first issue

#273 add seo
  .env
  src/app/blog-3-1/[name]/page.jsx
  src/app/blog-3-1/page.jsx
  src/app/book/page.jsx
  src/app/contacts/page.jsx
  src/app/layout.jsx
  src/app/page.jsx
  src/app/paid-priority-army/[name]/page.jsx
  src/app/paid-priority-army/page.jsx
  src/app/paid-priority-crime/[name]/page.jsx
  src/app/paid-priority-crime/page.jsx
  src/app/paid-priority-family/[name]/page.jsx
  src/app/paid-priority-family/page.jsx
  src/app/ru/blog-3-1/[name]/page.jsx
  src/app/ru/blog-3-1/page.jsx
  src/app/ru/book/page.jsx
  src/app/ru/contacts/page.jsx
  src/app/ru/page.jsx
  src/app/ru/paid-priority-army/[name]/page.jsx
  src/app/ru/paid-priority-army/page.jsx
  src/app/ru/paid-priority-crime/[name]/page.jsx
  src/app/ru/paid-priority-crime/page.jsx
  src/app/ru/paid-priority-family/[name]/page.jsx
  src/app/ru/paid-priority-family/page.jsx
  src/app/ru/services/page.jsx
  src/app/ru/teamactum/page.jsx
  src/app/services/page.jsx
  src/app/teamactum/page.jsx
  src/libs/pages/services/components/description/Description.jsx
  src/shared/helpers/queryBuilder.js
  src/shared/services/api/api.js
  src/shared/services/api/getSeo.js
Labels: duplicate, enhancement, good first issue

#274 fix bag
  src/app/ru/blog-3-1/[name]/page.jsx
  src/shared/helpers/queryBuilder.js
Labels: bug

#275 fix bag
  .env
  src/app/book/page.jsx
Labels: bug

#277 Admin panel
  .env
  src/app/blog-3-1/[name]/page.jsx
  src/app/paid-priority-army/[name]/page.jsx
  src/app/paid-priority-army/page.jsx
  src/app/paid-priority-crime/[name]/page.jsx
  src/app/paid-priority-crime/page.jsx
  src/app/paid-priority-family/[name]/page.jsx
  src/app/paid-priority-family/page.jsx
  src/app/ru/blog-3-1/[name]/page.jsx
  src/app/ru/paid-priority-army/[name]/page.jsx
  src/app/ru/paid-priority-army/page.jsx
  src/app/ru/paid-priority-crime/[name]/page.jsx
  src/app/ru/paid-priority-crime/page.jsx
  src/app/ru/paid-priority-family/[name]/page.jsx
  src/app/ru/paid-priority-family/page.jsx
  src/assets/json/error 2.json
  src/libs/components/about/About.jsx
  src/libs/components/about/About.module.scss
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/SelectNav/Select.jsx
  src/libs/pages/components/hero/HeroLawyers.jsx
  src/libs/pages/components/successfulBusiness/items/Items.jsx
  src/shared/components/arrow_menu/ArrowMenu.jsx
  src/shared/components/path/Path.jsx
  src/shared/components/path/Path.module.scss
  src/shared/helpers/queryBuilder.js
  src/shared/services/api/api.js
  src/shared/services/api/getFamilyLawyer.js
  src/shared/services/api/getFamilyLawyers.js
Labels: bug, duplicate, enhancement

#281 fix bag and refactoring
  src/app/services/page.jsx
  src/libs/components/about/About.jsx
  src/libs/components/currentPublication/CurrentPublication.jsx
  src/libs/components/ourDirections/criminalMatters/CriminalMattrs.jsx
  src/libs/components/ourDirections/criminalMatters/CriminalMattrs.module.scss
  src/libs/components/ourDirections/familyMatters/FamilyMattrs.jsx
  src/libs/components/ourDirections/familyMatters/FamilyMattrs.module.scss
  src/libs/components/ourDirections/militaryMatters/MilitaryMattrs.jsx
  src/libs/components/ourDirections/militaryMatters/MilitaryMattrs.module.scss
  src/libs/pages/services/components/about/Items.jsx
  src/libs/pages/services/components/about/Items.module.scss
  src/libs/pages/teamactum/items/Items.jsx
Labels: bug, duplicate

#284 fix bag , make request on reviews and refactoring ;
  .env
  next.config.js
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  src/app/api/route.js
  src/app/page.jsx
  src/libs/components/arrowCard/Arrow.jsx
  src/libs/components/card/Card.jsx
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/components/footer/Footer.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/hero/Animations.jsx
  src/libs/components/hero/Hero.jsx
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/SelectNav/Select.jsx
  src/libs/components/response/Response.jsx
  src/libs/components/response/list/ItemsList.jsx
  src/libs/components/response/list/desktop_animation/DesktopAnimation.jsx
  src/libs/pages/components/specialists/items/Items.module.scss
  src/shared/components/mobile_animation/MobileSlider.jsx
  src/shared/components/nestedPageHero/NestedHero.jsx
  src/shared/helpers/helpers.js
  src/shared/helpers/unPackageTelegramReview.js
Labels: bug, duplicate, enhancement, good first issue

#287 Admin panel
  public/sitemap-0.xml
  src/app/api/form/route.js
  src/app/api/hello.js
  src/app/api/rewiews/route.js
  src/app/page.jsx
  src/assets/json/reviews.json
  src/libs/components/arrowCard/Arrow.jsx
  src/libs/components/response/Response.jsx
  src/libs/components/response/libs/enums.js
  src/shared/components/form/Form.jsx
Labels: duplicate, enhancement, good first issue

#289 Admin panel
  .env
  src/app/credits-lawyer/[name]/page.jsx
  src/app/credits-lawyer/page.jsx
  src/app/paid-priority-consultation/[name]/page.jsx
  src/app/paid-priority-consultation/page.jsx
  src/app/paid-priority-land/[name]/page.jsx
  src/app/paid-priority-land/page.jsx
  src/app/polandlawyer-ua/[name]/page.jsx
  src/app/polandlawyer-ua/page.jsx
  src/app/services/administratyvni-spravy/[name]/page.jsx
  src/app/services/administratyvni-spravy/page.jsx
  src/assets/json/reviews.json
  src/libs/pages/services/components/lawyers/items/Items.jsx
  src/libs/pages/services/components/lawyers/items/Items.module.scss
Labels: enhancement

#290 fix bag
  src/app/api/form/route.js
  src/assets/json/reviews.json
Labels: bug

#291 fix bag
  next.config.js
  src/app/api/form/route.js
  src/shared/components/form/Form.jsx
Labels: bug

#292 fix bag
  next.config.js
  package.json
Labels: bug

#294 fix bag
  src/libs/components/response/Response.jsx
  src/libs/modal/formComponent/FormComponent.jsx
Labels: bug

#298 Admin panel
  src/assets/json/reviews.json
  src/libs/components/card/Card.jsx
  src/libs/components/header/Header.jsx
  src/libs/components/response/Response.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/shared/components/form/Form.jsx
  src/shared/enums/app/app.js
  src/shared/enums/app/form.js
  src/shared/enums/enum.js
  src/shared/helpers/sessionStorageManager.js
  src/shared/helpers/unPackageTelegramReview.js
  src/shared/hooks/hooks.js
Labels: bug, enhancement, good first issue

#300 fix bag
  .env
  src/app/layout.jsx
  src/app/paid-priority-army/[name]/page.jsx
  src/app/paid-priority-army/page.jsx
  src/app/paid-priority-consultation/[name]/page.jsx
  src/app/paid-priority-crime/[name]/page.jsx
  src/app/paid-priority-crime/page.jsx
  src/app/paid-priority-dtp/[name]/page.jsx
  src/app/paid-priority-family/[name]/page.jsx
  src/app/paid-priority-land/[name]/page.jsx
  src/app/polandlawyer-ua/[name]/page.jsx
  src/app/ru/paid-priority-army/[name]/page.jsx
  src/app/ru/paid-priority-army/page.jsx
  src/app/ru/paid-priority-crime/[name]/page.jsx
  src/app/ru/paid-priority-crime/page.jsx
  src/app/ru/paid-priority-family/[name]/page.jsx
  src/app/services/administratyvni-spravy/[name]/page.jsx
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/components/contactPanel/ContactPanel.module.scss
  src/libs/components/nav/Animated/ArrowOpen.jsx
  src/libs/components/nav/NavSelectItem/NavSelectItem.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/components/nav/SelectNav/Select.jsx
  src/libs/pages/components/QuestionList/Accordion.jsx
  src/libs/pages/components/aboutCards/AboutCards.jsx
  src/libs/pages/components/aboutCards/items/Items.jsx
  src/libs/pages/services/components/description/Description.jsx
  src/shared/components/arrow_menu/ArrowMenu.jsx
  src/shared/components/click/Click.jsx
Labels: bug, duplicate, enhancement

#301 New sitemap
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  scripts/generate-sitemap.js
  src/app/robots.js
  src/assets/json/reviews.json
  src/libs/components/about_company/AboutCompany.jsx
  src/libs/components/about_company/AboutCompany.module.scss
  src/libs/components/about_company/AboutGradients.module.scss
  src/libs/components/contactPanel/ContactPanel.module.scss
  src/libs/components/ourDirections/Direction.jsx
  src/libs/components/ourDirections/criminalMatters/CriminalMattrs.module.scss
  src/libs/components/ourDirections/familyMatters/FamilyMattrs.module.scss
  src/libs/components/ourDirections/militaryMatters/MilitaryMattrs.module.scss
  src/libs/components/response/Response.jsx
  src/libs/modal/formComponent/FormComponent.jsx
  src/libs/pages/components/QuestionList/QuestionsList.jsx
  src/shared/components/about/About.jsx
  src/shared/components/about/About.module.scss
Labels: bug

#303 fix bag
  src/libs/components/footer/Footer.module.scss
  src/libs/pages/components/QuestionList/Accordion.module.scss
  src/libs/pages/components/QuestionList/QuestionsList.jsx
Labels: bug, duplicate

#306 Admin panel
  .env
  src/app/book/page.jsx
  src/app/credits-lawyer/[name]/page.jsx
  src/app/credits-lawyer/page.jsx
  src/app/html-sitemap/[name]/page.jsx
  src/app/paid-priority-army/[name]/page.jsx
  src/app/paid-priority-army/page.jsx
  src/app/paid-priority-consultation/[name]/page.jsx
  src/app/paid-priority-consultation/page.jsx
  src/app/paid-priority-crime/[name]/page.jsx
  src/app/paid-priority-crime/page.jsx
  src/app/paid-priority-dtp/[name]/page.jsx
  src/app/paid-priority-dtp/page.jsx
  src/app/paid-priority-family/[name]/page.jsx
  src/app/paid-priority-family/page.jsx
  src/app/paid-priority-land/[name]/page.jsx
  src/app/paid-priority-land/page.jsx
  src/app/polandlawyer-ua/page.jsx
  src/app/ru/blog-3-1/[name]/page.jsx
  src/app/ru/blog-3-1/page.jsx
  src/app/ru/book/page.jsx
  src/app/ru/contacts/page.jsx
  src/app/ru/html-sitemap/page.jsx
  src/app/ru/not-found.jsx
  src/app/ru/page.jsx
  src/app/ru/paid-priority-army/[name]/page.jsx
  src/app/ru/paid-priority-crime/[name]/page.jsx
  src/app/ru/paid-priority-crime/page.jsx
  src/app/ru/paid-priority-family/[name]/page.jsx
  src/app/ru/paid-priority-family/page.jsx
  src/app/ru/services/page.jsx
  src/app/ru/teamactum/page.jsx
  src/app/services/administratyvni-spravy/[name]/page.jsx
  src/app/services/administratyvni-spravy/page.jsx
  src/assets/json/reviews.json
  src/libs/components/contactPanel/ContactPanel.jsx
  src/libs/components/footer/Footer.jsx
  src/libs/components/nav/Navigation.jsx
  src/libs/components/nav/SelectNav/Select.module.scss
  src/libs/modal/formComponent/FormComponent.jsx
  src/libs/pages/components/QuestionList/Accordion.jsx
  src/libs/pages/components/successfulBusiness/SuccessfulBusiness.jsx
  src/libs/pages/components/successfulBusiness/card/Card.jsx
  src/libs/pages/components/successfulBusiness/items/Items.jsx
  src/shared/components/about/About.module.scss
  src/shared/components/form/Form.jsx
  src/shared/components/formSection/FormSection.jsx
  src/shared/components/stepLawyers/StepsLawyers.jsx
  src/shared/components/stepLawyers/StepsLawyers.module.scss
  src/shared/helpers/sessionStorageManager.js
Labels: bug
